"""empty message

Revision ID: 2dd5c5836ac4
Revises: 
Create Date: 2023-02-11 12:34:06.306289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dd5c5836ac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('org_sector', sa.Enum('ACADEMIA', 'NGO', 'GOVT', 'MEDIA', 'BUSINESS', 'CSR', 'SOC_ENT', 'IDP', 'OTHER', name='orgsector'), nullable=True),
    sa.Column('foci', sa.ARRAY(sa.Enum('INDIGENOUS', 'LGBTI', 'REL_FREEDOM', 'WOMENS_RIGHTS', 'OTHER', name='wf_enum', native_enum=False)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org')
    # ### end Alembic commands ###
